// Snapshot startowy 2026/27. Dane centralne i wojewódzkie są oddzielone od save'a:
// po rozpoczęciu kariery terminarz oraz ruchy ligowe żyją już w świecie gry.

import { GENERATED_REGIONAL_PACKS } from "./regional-catalog.generated.mjs";

const source = "PZPN/WZPN i 90minut.pl — snapshot 2026/27";

export const V_LEAGUE_ASSOCIATIONS = ["Małopolski ZPN", "Mazowiecki ZPN", "Śląski ZPN", "Wielkopolski ZPN"];

export function regionalTier(association, competition) {
  const hasVLeague = V_LEAGUE_ASSOCIATIONS.includes(association);
  if (competition === "IV liga") return 5;
  if (competition === "V liga") return 6;
  const base = { "Klasa okręgowa": 6, "Klasa A": 7, "Klasa B": 8, "Klasa C": 9 }[competition] ?? 10;
  return base + (hasVLeague ? 1 : 0);
}

const CURATED_LEAGUE_PACKS = [
  { id: "ekstraklasa", association: "PZPN — rozgrywki centralne", district: "Polska", competition: "Ekstraklasa", group: "liga ogólnopolska", tier: 1, teams: ["Lech Poznań", "Legia Warszawa", "Górnik Zabrze", "Jagiellonia Białystok", "Wisła Kraków", "Piast Gliwice", "GKS Katowice", "Pogoń Szczecin", "Korona Kielce", "Zagłębie Lubin", "Cracovia", "Radomiak Radom", "Widzew Łódź", "Śląsk Wrocław", "Motor Lublin", "Wisła Płock", "Wieczysta Kraków", "Raków Częstochowa"], source },
  { id: "pierwsza-liga", association: "PZPN — rozgrywki centralne", district: "Polska", competition: "I liga", group: "liga ogólnopolska", tier: 2, teams: ["Pogoń Grodzisk Mazowiecki", "Chrobry Głogów", "Arka Gdynia", "Polonia Warszawa", "ŁKS Łódź", "Bruk-Bet Termalica Nieciecza", "Lechia Gdańsk", "Miedź Legnica", "Odra Opole", "Pogoń Siedlce", "Polonia Bytom", "Puszcza Niepołomice", "Stal Mielec", "Stal Rzeszów", "Ruch Chorzów", "Warta Poznań", "Podbeskidzie Bielsko-Biała", "Unia Skierniewice"], source },
  { id: "druga-liga", association: "PZPN — rozgrywki centralne", district: "Polska", competition: "II liga", group: "liga ogólnopolska", tier: 3, teams: ["Avia Świdnik", "Chojniczanka Chojnice", "GKS Tychy", "Górnik Łęczna", "Hutnik Kraków", "Lechia Zielona Góra", "Legia II Warszawa", "Olimpia Grudziądz", "Podhale Nowy Targ", "Rekord Bielsko-Biała", "Resovia Rzeszów", "Sandecja Nowy Sącz", "Sokół Kleczew", "Stal Stalowa Wola", "Śląsk II Wrocław", "Świt Szczecin", "Zawisza Bydgoszcz", "Znicz Pruszków"], source },

  { id: "trzecia-liga-i", association: "PZPN — rozgrywki centralne", district: "grupa I", competition: "III liga", group: "grupa I", tier: 4, teams: ["Jagiellonia II Białystok", "KTS Weszło", "KS CK Troszyn", "Lechia Tomaszów Mazowiecki", "ŁKS Łomża", "ŁKS II Łódź", "Mazovia Mińsk Mazowiecki", "Mławianka Mława", "Olimpia Elbląg", "Olimpia Zambrów", "Pelikan Łowicz", "Polonia Lidzbark Warmiński", "Świt Nowy Dwór Mazowiecki", "Warta Sieradz", "Widzew II Łódź", "Wisła II Płock", "Wigry Suwałki", "Ząbkovia Ząbki"], source },
  { id: "trzecia-liga-ii", association: "PZPN — rozgrywki centralne", district: "grupa II", competition: "III liga", group: "grupa II", tier: 4, teams: ["Bałtyk Koszalin", "Błękitni Stargard", "Chemik Bydgoszcz", "Elana Toruń", "Flota Świnoujście", "Gedania Gdańsk", "Grom Nowy Staw", "KKS 1925 Kalisz", "Kluczevia Stargard", "Kotwica Kórnik", "Lech II Poznań", "Lipno Stęszew", "Noteć Czarnków", "Polonia Środa Wielkopolska", "Unia Swarzędz", "Victoria Września", "Wda Świecie", "Wikęd Luzino"], source },
  { id: "trzecia-liga-iii", association: "PZPN — rozgrywki centralne", district: "grupa III", competition: "III liga", group: "grupa III", tier: 4, teams: ["Barycz Sułów", "Carina Gubin", "Górnik Polkowice", "Karkonosze Jelenia Góra", "KS Stilon Gorzów Wielkopolski", "LKS Goczałkowice Zdrój", "Miedź II Legnica", "MKS Kluczbork", "Odra Bytom Odrzański", "ROW 1964 Rybnik", "Polonia Nysa", "Raków II Częstochowa", "Sparta Katowice", "Stal Brzeg", "Ślęza Wrocław", "Warta Gorzów Wielkopolski", "Zagłębie II Lubin", "Zagłębie Sosnowiec"], source },
  { id: "trzecia-liga-iv", association: "PZPN — rozgrywki centralne", district: "grupa IV", competition: "III liga", group: "grupa IV", tier: 4, teams: ["AKS 1947 Busko-Zdrój", "Chełmianka Chełm", "Czarni Połaniec", "Hetman Zamość", "JKS 1909 Jarosław", "Korona II Kielce", "KSZO 1929 Ostrowiec Świętokrzyski", "Moravia Morawica", "Naprzód Jędrzejów", "Podlasie Biała Podlaska", "Pogoń-Sokół Lubaczów", "Siarka Tarnobrzeg", "Sokół Kolbuszowa Dolna", "Star Starachowice", "Wieczysta II Kraków", "Wisła II Kraków", "Wisłoka Dębica", "Wiślanie Skawina"], source },

  { id: "iv-dolnoslaska", association: "Dolnośląski ZPN", district: "województwo", competition: "IV liga", group: "dolnośląska", tier: 5, teams: ["Piast Żmigród", "Lechia Dzierżoniów", "Chrobry II Głogów", "Błyskawica Gać", "Prochowiczanka Prochowice", "Górnik Złotoryja", "Moto Jelcz Oława", "Orzeł Ząbkowice Śląskie", "GKS Mirków/Długołęka", "Piast Nowa Ruda", "Iskra Księginice", "AKS Strzegom", "Polonia Środa Śląska", "GKS Raciborowice", "Odra Ścinawa", "Polonia-Stal Świdnica", "Polonia Bielany Wrocławskie", "WKS Wierzbice"], source },
  { id: "iv-kujawsko-pomorska", association: "Kujawsko-Pomorski ZPN", district: "województwo", competition: "IV liga", group: "kujawsko-pomorska", tier: 5, teams: ["Pogoń Mogilno", "Unia Solec Kujawski", "Wisła Dobrzyń nad Wisłą", "Unia Wąbrzeźno", "Mustang Ostaszewo", "Kujawiak Kowal", "Sparta Brodnica", "Orlęta Aleksandrów Kujawski", "Victoria Czernikowo", "Cuiavia Inowrocław", "Start Pruszcz", "Lech Rypin", "Łokietek Brześć Kujawski", "Tłuchowia Tłuchowo", "Rawys Raciąż", "Pomorzanin Toruń", "Noteć Gębice", "Skrwa Skrwilno"], source },
  { id: "iv-lubelska", association: "Lubelski ZPN", district: "województwo", competition: "IV liga", group: "lubelska", tier: 5, teams: ["Lewart Lubartów", "Łada 1945 Biłgoraj", "Tomasovia Tomaszów Lubelski", "Lublinianka Lublin", "Tur Milejów", "Orlęta Radzyń Podlaski", "Janowianka Janów Lubelski", "Bug Hanna", "Granit Bychawa", "MKS Ryki", "Orlęta Łuków", "Świdniczanka Świdnik", "Powiślak Końskowola", "Victoria Łukowa", "Avia II Świdnik", "Górnik II Łęczna"], source },
  { id: "iv-lubuska", association: "Lubuski ZPN", district: "województwo", competition: "IV liga", group: "lubuska", tier: 5, teams: ["Polonia Słubice", "Odra Nietków", "Sprotavia Szprotawa", "Ilanka Rzepin", "Lechia II Zielona Góra", "Pogoń Świebodzin", "KP Piast Iłowa", "Victoria Szczaniec", "Czarni Żagań", "Róża Różanki", "Dozamet Nowa Sól", "Łucznik Strzelce Krajeńskie", "Stal Sulęcin", "Piast Karnin", "Celuloza Kostrzyn nad Odrą", "Promień Żary", "Korona Kożuchów", "Pogoń Skwierzyna"], source },
  { id: "iv-lodzka", association: "Łódzki ZPN", district: "województwo", competition: "IV liga", group: "łódzka", tier: 5, teams: ["Sokół Aleksandrów Łódzki", "AKS SMS Łódź", "RKS Radomsko", "Orkan Buczek", "Ceramika Opoczno", "Boruta Zgierz", "ŁKS III Łódź", "KS Kutno", "Stal Głowno", "Zryw Wygoda", "Polonia Piotrków Trybunalski", "Zjednoczeni Stryków", "GKS Bełchatów", "Orzeł Parzęczew", "Włókniarz Pabianice", "Concordia Piotrków Trybunalski", "Ekolog Wojsławice", "LZS Justynów"], source },
  { id: "iv-malopolska", association: "Małopolski ZPN", district: "województwo", competition: "IV liga", group: "małopolska", tier: 5, teams: ["Beskid Andrychów", "Orzeł Ryczów", "Glinik Gorlice", "Dalin Myślenice", "Poprad Muszyna", "Lubań Maniowy", "Kalwarianka Kalwaria Zebrzydowska", "Bocheński KS", "Limanovia Limanowa", "Pcimianka Pcim", "Watra Białka Tatrzańska", "Hutnik II Kraków", "Unia Tarnów", "Cracovia II", "Wolania Wola Rzędzińska", "Bruk-Bet Termalica II Nieciecza", "Victoria 1918 Jaworzno", "Błękitni Modlnica"], source },
  { id: "iv-mazowiecka", association: "Mazowiecki ZPN", district: "województwo", competition: "IV liga", group: "mazowiecka", tier: 5, teams: ["Victoria Sulejówek", "Hutnik Warszawa", "Ursus Warszawa", "Legionovia Legionowo", "MKS Piaseczno", "KS Łomianki", "Błonianka Błonie", "Oskar Przysucha", "Mszczonowianka Mszczonów", "Makowianka Maków Mazowiecki", "Mazur Karczew", "MKS Przasnysz", "Talent Warszawa", "Broń Radom", "Polonia II Warszawa", "Nadnarwianka Pułtusk", "Podlasie Sokołów Podlaski", "Energia Kozienice"], source },
  { id: "iv-opolska", association: "Opolski ZPN", district: "województwo", competition: "IV liga", group: "opolska", tier: 5, teams: ["Ruch Zdzieszowice", "Małapanew Ozimek", "Odra II Opole", "LZS Domaszkowice", "Start Namysłów", "Fortuna Głogówek", "LZS Starościn", "Śląsk Łubniany", "Porawie Większyce", "LZS Starowice Dolne", "LKS Kadłub", "Stal Zawadzkie", "MKS Gogolin", "Orzeł Branice"], source },
  { id: "podkarpacka-iv", association: "Podkarpacki ZPN", district: "województwo", competition: "IV liga", group: "podkarpacka", tier: 5, teams: ["Izolator Boguchwała", "Igloopol Dębica", "Stal Łańcut", "Legion Pilzno", "Sokół Nisko", "Polonia Przemyśl", "KS Wiązownica", "Czarni 1910 Jasło", "Błękitni Ropczyce", "Geo-Eko Ekoball Stal Sanok", "Wisłok Wiśniowa", "Radomyślanka Radomyśl Wielki", "Pogoń-Sokół II Lubaczów", "Sokół Sieniawa", "Górnik Strachocina", "Stal II Rzeszów", "Strug Tyczyn", "Pogoń Leżajsk"], source },
  { id: "iv-podlaska", association: "Podlaski ZPN", district: "województwo", competition: "IV liga", group: "podlaska", tier: 5, teams: ["Warmia Grajewo", "Ruch Wysokie Mazowieckie", "Wissa Szczuczyn", "Pionier Brańsk", "Tur Bielsk Podlaski", "Czarni Czarna Białostocka", "Hetman Tykocin", "Promień Mońki", "KS Śniadowo", "Supraślanka Supraśl", "Krypnianka Krypno", "KS Michałowo", "LZS Krynki", "KS Wasilków", "ŁKS II Łomża", "Pomorzanka Sejny"], source },
  { id: "iv-pomorska", association: "Pomorski ZPN", district: "województwo", competition: "IV liga", group: "pomorska", tier: 5, teams: ["KP Starogard Gdański", "Gryf Słupsk", "Arka II Gdynia", "Czarni Pruszcz Gdański", "Chojniczanka II Chojnice", "Anioły Garczegorze", "Wierzyca Pelplin", "Jaguar Gdańsk", "Gryf Wejherowo", "Pogoń Lębork", "Sokół Bożepole Wielkie", "Stolem Gniewino", "Powiśle Dzierzgoń", "Cartusia Kartuzy", "Stoczniowiec Gdańsk", "Radunia Stężyca", "Dolina Speranda Niepoględzie", "Sparta Sycewice"], source },
  { id: "iv-slaska", association: "Śląski ZPN", district: "województwo", competition: "IV liga", group: "I liga śląska", tier: 5, teams: ["MRKS Czechowice-Dziedzice", "Ruch II Chorzów", "Unia Turza Śląska", "Polonia Łaziska Górne", "Ruch Radzionków", "GKS II Katowice", "Przemsza Siewierz", "Spójnia Landek", "Podbeskidzie II Bielsko-Biała", "Drama Zbrosławice", "Szombierki Bytom", "Podlesianka Katowice", "Kuźnia Ustroń", "Rozwój Katowice", "Piast II Gliwice", "Gwarek Tarnowskie Góry", "LKS Bełk", "Victoria Częstochowa"], source },
  { id: "iv-swietokrzyska", association: "Świętokrzyski ZPN", district: "województwo", competition: "IV liga", group: "świętokrzyska", tier: 5, teams: ["Arka Pawłów", "Neptun Końskie", "Orlęta Kielce", "GKS Rudki", "GKS Nowiny", "Spartakus Daleszyce", "Korona III Kielce", "Klimontowianka Klimontów", "Victoria Skalbmierz", "Granat Skarżysko-Kamienna", "Wierna Małogoszcz", "Alit Ożarów", "Hetman Włoszczowa", "Orlicz Suchedniów", "Sparta Kazimierza Wielka", "OKS Opatów", "KKP Korona Kielce", "Wicher Miedziana Góra"], source },
  { id: "iv-warminsko-mazurska", association: "Warmińsko-Mazurski ZPN", district: "województwo", competition: "IV liga", group: "warmińsko-mazurska", tier: 5, teams: ["Stomil Olsztyn", "Concordia Elbląg", "DKS Dobre Miasto", "Sokół Ostróda", "Tęcza Biskupiec", "Mamry Giżycko", "Start Nidzica", "Rominta Gołdap", "Pisa Barczewo", "Granica Kętrzyn", "Mazur Ełk", "GKS Wikielec", "Znicz Biała Piska", "Naki Olsztyn", "Zatoka Braniewo", "Polonia Pasłęk"], source },
  { id: "iv-wielkopolska", association: "Wielkopolski ZPN", district: "województwo", competition: "IV liga", group: "wielkopolska", tier: 5, teams: ["Polonia Chodzież", "Mieszko Gniezno", "Polonia Golina", "Górnik Konin", "Piast Kobylnica", "Kania Gostyń", "Warta Śrem", "Huragan Pobiedziska", "Obra Kościan", "Ostrovia 1909 Ostrów Wielkopolski", "Polonia 1912 Leszno", "Nielba Wągrowiec", "LKS Gołuchów", "Pogoń Nowe Skalmierzyce", "Kłos Budzyń", "Avia Kamionki", "Meblorz Swarzędz", "Astra Krotoszyn"], source },
  { id: "iv-zachodniopomorska", association: "Zachodniopomorski ZPN", district: "województwo", competition: "IV liga", group: "zachodniopomorska", tier: 5, teams: ["Iskierka Śmierdnica", "Dąb Dębno", "Biali Sądów", "Sparta Gryfice", "Gwardia Koszalin", "Chemik Police", "Świt II Szczecin", "Astra Ustronie Morskie", "Ina Ińsko", "Orzeł Wałcz", "Pogoń II Szczecin", "Wybrzeże Rewalskie Rewal", "MKS Kotwica Kołobrzeg", "Arkonia Szczecin", "Leśnik Manowo", "CRS Barlinek"], source },

  { id: "v-malopolska-wschod", association: "Małopolski ZPN", district: "województwo", competition: "V liga", group: "małopolska wschód", tier: 6, teams: ["Wisła Czarny Dunajec", "Turbacz Mszana Dolna", "Sokół Słopnice", "Poprad Rytro", "Gród Podegrodzie", "Dąbrovia Dąbrowa Tarnowska", "MLKS Żabno", "Podhale II Nowy Targ", "Dunajec Nowy Sącz", "Kolejarz Stróże", "Łosoś Łososina Dolna", "LKS Nowa Jastrząbka", "Tarnovia Tarnów", "LKS Gnojnik", "Orawa Jabłonka", "Okocimski Brzesko"], source },
  { id: "v-malopolska-zachod", association: "Małopolski ZPN", district: "województwo", competition: "V liga", group: "małopolska zachód", tier: 6, teams: ["Orzeł Myślenice", "Radziszowianka Radziszów", "Niwa Nowa Wieś", "Michałowianka Michałowice", "Wróblowianka Wróblowice Kraków", "KS Chełmek", "Kabel Kraków", "Tempo Białka", "Garbarnia Kraków", "Puszcza II Niepołomice", "LKS Bobrek", "Przebój Wolbrom", "Kmita Zabierzów", "Sokół Kocmyrzów Baranówka", "Świt Krzeszowice", "MKS Trzebinia"], source },
  { id: "v-mazowiecka-i", association: "Mazowiecki ZPN", district: "województwo", competition: "V liga", group: "mazowiecka I", tier: 6, teams: ["Narew 1962 Ostrołęka", "Naprzód Zielonki", "Gladiator Słoszewo", "Drukarz Warszawa", "Ożarowianka Ożarów Mazowiecki", "Huragan Wołomin", "PAF Płońsk", "Bug Wyszków", "Białe Orły Warszawa", "Znicz II Pruszków", "Marcovia Marki AP", "Wicher Kobyłka", "Escola Varsovia Warszawa", "Sokół Serock", "Błękitni Gąbin", "Kasztelan Sierpc"], source },
  { id: "v-mazowiecka-ii", association: "Mazowiecki ZPN", district: "województwo", competition: "V liga", group: "mazowiecka II", tier: 6, teams: ["Józefovia Józefów", "Wilga Garwolin", "Powiślanka Lipsko", "Jodła Jedlnia-Letnisko", "Champion Warszawa", "Ursus II Warszawa", "Radomiak II Radom", "Pilica Białobrzegi", "Żyrardowianka Żyrardów", "Pogoń II Siedlce", "Tygrys Huta Mińska", "LKS Jedlińsk", "LKS Chlebnia", "Proch Pionki", "Perła Złotokłos", "Wektra Zbuczyn"], source },
  { id: "v-slaska-i", association: "Śląski ZPN", district: "województwo", competition: "V liga", group: "II liga śląska I", tier: 6, teams: ["Gwarek Ornontowice", "Górnik Piaski Czeladź", "Pilica Koniecpol", "Odra Miasteczko Śląskie", "Zagłębie II Sosnowiec", "Unia Rędziny", "Śląsk Świętochłowice", "CKS Czeladź", "Sarmacja Będzin", "Liswarta Krzepice", "Orzeł Miedary", "Unia Dąbrowa Górnicza", "Jedność 32 Przyszowice", "AKS Mikołów", "Zieloni Żarki", "Start Sierakowice"], source },
  { id: "v-slaska-ii", association: "Śląski ZPN", district: "województwo", competition: "V liga", group: "II liga śląska II", tier: 6, teams: ["Stal-Śrubiarnia Żywiec", "LKS II Goczałkowice Zdrój", "Błyskawica Drogomyśl", "Rekord II Bielsko-Biała", "Start Mszana", "LKS Czaniec", "LKS Tworków", "Tempo Puńców", "Beskid 09 Skoczów", "MKS Lędziny", "Pasjonat Dankowice", "Góral Istebna", "Forteca Świerklany", "GLKS Wilkowice", "BKS Stal Bielsko-Biała", "Pniówek Pawłowice Śląskie"], source },
  { id: "v-wielkopolska-i", association: "Wielkopolski ZPN", district: "województwo", competition: "V liga", group: "wielkopolska I", tier: 6, teams: ["Warta Międzychód", "Wełna Skoki", "Zamek Gołańcz", "Sparta Oborniki", "Tarnovia Tarnowo Podgórne", "Polonia Jastrowie", "Dyskobolia Grodzisk Wielkopolski", "KP Piła", "Korona Stróżewo", "Lubuszanin Trzcianka", "Sparta Złotów", "Kłos Gałowo", "Obra Zbąszyń", "Sparta Szamotuły", "GKS Golęczewo", "Noteć Dziembowo"], source },
  { id: "v-wielkopolska-ii", association: "Wielkopolski ZPN", district: "województwo", competition: "V liga", group: "wielkopolska II", tier: 6, teams: ["Olimpia Koło", "Stella Luboń", "Unia II Swarzędz", "Warta II Poznań", "Wiara Lecha Poznań", "SKP Słupca", "Orkan Jarosławiec", "Kłos Zaniemyśl", "Wilki Wilczyn", "UKS Śrem", "Polonia II Środa Wielkopolska", "1922 Lechia Kostrzyn", "Poznańska 13 Poznań", "Polanin Strzałkowo", "Tulisia Tuliszków", "Polonus Kazimierz Biskupi"], source },
  { id: "v-wielkopolska-iii", association: "Wielkopolski ZPN", district: "województwo", competition: "V liga", group: "wielkopolska III", tier: 6, teams: ["Orzeł Kawęczyn", "Korona Piaski", "Jarota Jarocin", "Rawia Rawicz", "Centra Ostrów Wielkopolski", "Polonia 1912 II Leszno", "KKS II Kalisz", "LKS Jankowy", "Polonia Kępno", "Orla Jutrosin", "Krobianka Krobia", "Tęcza/Osa Osieczna", "Dąbroczanka Pępowo", "Sokół Bralin", "Korona Wilkowice", "Zawisza Łęka Opatowska"], source },

  { id: "podkarpacka-okregowa-jaroslaw", association: "Podkarpacki ZPN", district: "Jarosław", competition: "Klasa okręgowa", group: "Jarosław", tier: 6, teams: ["Czuwaj Przemyśl", "MKS Kańczuga", "Gorliczanka Gorliczyna", "Płomień Morawsko", "Orzeł Przeworsk", "Piast Tuczempy", "Wiraż Chłopice", "Sanoczanka Święte", "KS Arłamów", "Zdrój Horyniec", "Czarni Pawłosiów", "Start Lisie Jamy", "Orzeł Torki", "Wólczanka Wólka Pełkińska", "Start Pruchnik", "Promyk Urzejowice"], source },
  { id: "podkarpacka-a-krosno-ii", association: "Podkarpacki ZPN", district: "Krosno", competition: "Klasa A", group: "Krosno II", tier: 7, teams: ["Karpaty Krosno", "LKS Górki", "Karpaty Klimkówka", "LKS Wzdów", "Burza Rogi", "Płomień Zmiennica", "Iskra Przysietnica", "Kotwica Korczyna", "Tęcza Zręcin", "LKS Haczów", "LKS Lubatowa", "LKS Lubatówka", "LKS Głowienka", "Sokół Domaradz", "Beskid Posada Górna"], source },
  { id: "podkarpacka-a-jaroslaw", association: "Podkarpacki ZPN", district: "Jarosław", competition: "Klasa A", group: "Jarosław I", tier: 7, teams: ["Dąb Dobkowice", "Pogórze Rokietnica", "Piast II Tuczempy", "Santos Piwoda", "LKS Manasterz", "MKS Radymno", "LKS Skołoszów", "Hetman Laszki", "Fredro Surochów", "Wisznia Nienowice", "Łęk Ostrów", "KS Szówsko", "Łęg Łowce", "Korona Tuchla"], source },
  { id: "podkarpacka-b-jaroslaw", association: "Podkarpacki ZPN", district: "Jarosław", competition: "Klasa B", group: "Jarosław I", tier: 8, teams: ["Tęcza Jankowice", "KS Węgierka", "Wesoła Zadąbrowie", "Syrenka Roźwienica", "Szkło Młyny", "Wietlin", "Strażak Sośnica", "Sanovia Michałówka", "Victoria Kidałowice", "Przedmieście Jarosław", "LKS Munina", "LKS Duńkowice", "Łazowianka Łazy", "Olimpia Boratyn"], source },

  { id: "slaska-okregowa-rybnik-raciborz", association: "Śląski ZPN", district: "Rybnik", competition: "Klasa okręgowa", group: "Racibórz–Rybnik", tier: 7, teams: ["Sparta Żory", "Unia Racibórz", "Unia II Turza Śląska", "Górnik Radlin", "Przyszłość Rogów", "Ruch Stanowice", "TKKF Sokół Chwałęcice", "Kolejarz Chałupki", "LKS Krzyżanowice", "Naprzód Borucin", "Naprzód Czyżowice", "KS 1905 Krzanowice", "Dąb Gaszowice", "LKS 1908 Nędza", "Silesia Lubomia", "Czarni Gorzyce"], source },
  { id: "slaska-a-rybnik-i", association: "Śląski ZPN", district: "Rybnik", competition: "Klasa A", group: "Rybnik I", tier: 8, teams: ["MKS Czerwionka", "Jedność Jejkowice", "Rymer Rybnik", "Naprzód Rydułtowy", "KP Kamień", "KS Szczerbice", "Górnik Boguszowice", "MKS 32 Radziejów-Popielów", "Jedność Grabownia", "Płomień Czuchów", "Dąb II Gaszowice", "Płomień Ochojec"], source },
  { id: "slaska-a-rybnik-ii", association: "Śląski ZPN", district: "Rybnik", competition: "Klasa A", group: "Rybnik II", tier: 8, teams: ["Polonia Marklowice", "Płomień Połomia", "Polonia Łaziska Rybnickie", "Olza Godów", "Orzeł Jankowice", "Iskra Rowień Żory", "Gwiazda Skrzyszów", "KS 27 Gołkowice", "Borowik Szczejkowice", "LKS Baranowice Żory", "Wicher Wilchwy Wodzisław Śląski", "Granica Ruptawa Jastrzębie Zdrój"], source },
  { id: "slaska-b-rybnik-i", association: "Śląski ZPN", district: "Rybnik", competition: "Klasa B", group: "Rybnik I", tier: 9, teams: ["Zuch Orzepowice", "Dąb Dębieńsko", "LKS Górki Śląskie", "Polonia Niewiadom", "Naprzód II Rydułtowy", "KS Wielopole", "Płomień II Ochojec", "Górnik II Radlin", "KS 47 Wielopole", "Rymer II Rybnik", "Inter II Krostoszowice", "Pierwszy Chwałowice"], source },
  { id: "slaska-b-rybnik-ii", association: "Śląski ZPN", district: "Rybnik", competition: "Klasa B", group: "Rybnik II", tier: 9, teams: ["Rapid Wodzisław", "LKS II Baranowice", "GKS 62 Jastrzębie", "Żar Szeroka", "KS 27 II Gołkowice", "Odra Wodzisław", "LKS Skrbeńsko", "Polaris Żory", "Start Kleszczów", "Zryw Bzie", "Start II Mszana", "KS 25 Kokoszyce"], source },
];

function normalized(value) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function representsSameGroup(candidate, imported) {
  if (candidate.association !== imported.association || candidate.competition !== imported.competition) return false;
  if (normalized(candidate.group) === normalized(imported.group)) return true;
  const importedTeams = new Set(imported.teams.map(normalized));
  const overlap = candidate.teams.filter((team) => importedTeams.has(normalized(team))).length;
  return overlap >= Math.min(6, Math.ceil(Math.min(candidate.teams.length, imported.teams.length) / 2));
}

// Dane centralne pozostają kuratorowane ręcznie. Regionalny katalog pochodzi z jednego
// snapshotu 2026/27; ręczne pakiety uzupełniają wyłącznie grupy pominięte w imporcie.
const centralPacks = CURATED_LEAGUE_PACKS.filter((pack) => pack.tier <= 4);
const missingCuratedRegionalPacks = CURATED_LEAGUE_PACKS
  .filter((pack) => pack.tier > 4)
  .filter((pack) => !GENERATED_REGIONAL_PACKS.some((imported) => representsSameGroup(pack, imported)));

export const VERIFIED_LEAGUE_PACKS = [
  ...centralPacks,
  ...GENERATED_REGIONAL_PACKS,
  ...missingCuratedRegionalPacks,
];

export const LEAGUE_CATALOG_STATS = Object.freeze({
  associations: new Set(VERIFIED_LEAGUE_PACKS.filter((pack) => pack.tier > 4).map((pack) => pack.association)).size,
  groups: VERIFIED_LEAGUE_PACKS.length,
  teams: VERIFIED_LEAGUE_PACKS.reduce((total, pack) => total + pack.teams.length, 0),
});
