"use client";
import {useState} from 'react';
import {activeCareer} from './save-storage';
import {testerReport} from '../lib/tester-report.mjs';
export function TesterTools(){
 const [category,setCategory]=useState('Błąd rozgrywki');const [description,setDescription]=useState('');const [status,setStatus]=useState('');
 function download(){if(description.trim().length<12){setStatus('Napisz, co kliknięto i co się wydarzyło.');return;}const report=testerReport(activeCareer(),{category,description},{width:window.innerWidth,height:window.innerHeight,touch:navigator.maxTouchPoints>0});const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='TEN-TRENER-zgloszenie.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Plik przygotowany. Wyślij go organizatorowi testów razem ze zrzutem ekranu. Gra nie wysłała go automatycznie.');}
 return <details className="tester-tools"><summary>Testy i zgłoszenie problemu</summary><p><a href="/tester-guide.html" target="_blank" rel="noreferrer">Instrukcja dla testerów ↗</a></p><label>Rodzaj zgłoszenia<select value={category} onChange={e=>setCategory(e.target.value)}><option>Błąd rozgrywki</option><option>Zapis lub wczytanie</option><option>Obsługa na telefonie / PC</option><option>Nuda lub powtarzalność</option><option>Nielogiczne zdarzenie</option><option>Pomysł na poprawę</option></select></label><label>Co się wydarzyło?<textarea value={description} maxLength={4000} rows={4} placeholder="Np. po zakończeniu meczu zamknąłem raport, wróciłem na pulpit i… Oczekiwałem…" onChange={e=>setDescription(e.target.value)}/></label><small>Plik zawiera opis, wersję gry i stan rozgrywki potrzebny do sprawdzenia błędu. Nie zawiera nazwiska trenera ani pełnego zapisu. Wpisz tylko informacje dotyczące gry.</small><button type="button" onClick={download}>Pobierz zgłoszenie</button><p role="status">{status}</p></details>;
}
