"use client";
import { useEffect, useRef, useState } from "react";
import { TesterTools } from "./tester-tools";
import { BUILD, SAVE_KEY } from "./game-data";
import { activeCareer, readCareer, storeCareer } from "./save-storage";

const THEMES = [
  { id:"redakcja", name:"Redakcja", tag:"01 / SPORTOWY DZIENNIK", description:"Biel, drukarska czerń i czerwień. Krótkie komunikaty, wyraźna hierarchia." },
  { id:"manager", name:"Manager 98", tag:"02 / PIERWSZY PECET", description:"Stalowe okna, granatowe belki i przyciski jak w menedżerach lat 90." },
  { id:"teletext", name:"Telegazeta", tag:"03 / STRONA 201", description:"Czarne tło, duże cyfry i kolorowe zakładki. Wynik jest najważniejszy." },
  { id:"stadion", name:"Wieczór na stadionie", tag:"04 / POD JUPITERAMI", description:"Chłodny grafit, białe litery i zieleń murawy. Spokojny wariant nocny." },
];
export function ThemeButton() { return <button className="theme-open" onClick={()=>window.dispatchEvent(new Event("open-theme-studio"))} aria-label="Wygląd, zapis i pomoc">◧ <span>Wygląd i zapis</span></button>; }
export function ThemeStudio() {
  const [open,setOpen]=useState(false); const [theme,setTheme]=useState("redakcja"); const [message,setMessage]=useState("");
  const dialog=useRef<HTMLDialogElement>(null); const file=useRef<HTMLInputElement>(null);
  useEffect(()=>{ let saved="redakcja"; try { saved=localStorage.getItem("ten-trener-theme")??saved; } catch {} if(!THEMES.some(t=>t.id===saved)) saved="redakcja"; document.documentElement.dataset.theme=saved; setTheme(saved); const show=()=>setOpen(true); window.addEventListener("open-theme-studio",show); return()=>window.removeEventListener("open-theme-studio",show); },[]);
  useEffect(()=>{ if(open) dialog.current?.showModal(); else dialog.current?.close(); },[open]);
  const choose=(id:string)=>{setTheme(id);document.documentElement.dataset.theme=id;try{localStorage.setItem("ten-trener-theme",id);}catch{}};
  const download=async()=>{const current=activeCareer();let raw=current?JSON.stringify(current):localStorage.getItem(SAVE_KEY);if(raw&&!current)raw=JSON.stringify(await readCareer(raw));if(!raw){setMessage("Najpierw rozpocznij karierę.");return;} const blob=new Blob([raw],{type:"application/json"}); const url=URL.createObjectURL(blob); const link=document.createElement("a");link.href=url;link.download="TEN-TRENER-kariera.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Kopia kariery została przygotowana do pobrania.");};
  const restore=async(f?:File)=>{if(!f)return;try{if(f.size>20_000_000)throw Error();const save=await readCareer(await f.text());const old=localStorage.getItem(SAVE_KEY);if(old)localStorage.setItem(SAVE_KEY+"-backup",old);await storeCareer(save);window.dispatchEvent(new Event("restore-career"));setMessage("Wczytano karierę. Poprzedni zapis zachowano jako kopię.");setOpen(false);}catch{setMessage("Nie udało się wczytać pliku. Obecny zapis pozostał bez zmian.");}};
  return <dialog ref={dialog} className="theme-studio" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="studio-title"><header><div><small>TWÓJ EGZEMPLARZ GRY</small><h2 id="studio-title">Wybierz swój klimat.</h2></div><button onClick={()=>setOpen(false)} aria-label="Zamknij ustawienia">✕</button></header><div className="theme-options">{THEMES.map(t=><button key={t.id} className={`theme-option sample-${t.id} ${theme===t.id?"selected":""}`} onClick={()=>choose(t.id)} aria-pressed={theme===t.id}><small>{t.tag}</small><div className="theme-sample"><b>TEN TRENER</b><span>POLONIA <strong>2 : 1</strong> ORZEŁ</span><i>67′ &nbsp; Twoja decyzja →</i></div><h3>{t.name}{theme===t.id?" ✓":""}</h3><p>{t.description}</p></button>)}</div><section className="save-tools"><h3>Twoja kariera</h3><p>Zapis automatyczny po decyzjach i meczu. Kopia do pliku pozwala przenieść grę na inny telefon lub komputer.</p><button onClick={download}>Pobierz kopię zapisu</button><button onClick={()=>file.current?.click()}>Wczytaj kopię z pliku</button><input ref={file} type="file" accept=".json,.txt,application/json,text/plain" hidden onChange={e=>restore(e.target.files?.[0])}/><p role="status">{message}</p></section><details><summary>Jak grać? Trzy kroki między meczami</summary><ol><li>Przeczytaj sprawę na pulpicie. Wybór pokazuje możliwe zyski i koszty; po decyzji zobaczysz faktyczne zmiany.</li><li>Wybierz plan drużyny i mikrocykl. Regeneracja odnawia kondycję; trening realizujesz raz pomiędzy spotkaniami.</li><li>Rozegraj mecz. W kluczowych chwilach gra czeka na decyzję. Raport zamkniesz i wrócisz do przygotowań.</li></ol><p>Wypalenie dotyczy trenera. Kondycja dotyczy drużyny. Wyższy OVR zwiększa szanse, lecz nie gwarantuje zwycięstwa.</p></details><TesterTools /><p><button className="text-action" onClick={() => { setOpen(false); window.dispatchEvent(new Event("open-about-project")); }}>O projekcie i tej wersji</button></p><p className="beta-note">{BUILD}. Liga i wieloletnia kariera są grywalne. Awanse świata kariery używają uproszczonych reguł: zwycięzcy grup konkurują punktami na mecz o 1–3 miejsca wyżej. Oficjalne baraże, Puchar Polski i Europa są jeszcze poza tą wersją. Zmiana klubu jest obecnie dostępna latem; zimą pojawia się zainteresowanie. Składy lig wymagają weryfikacji przed wydaniem publicznym.</p><footer><button className="primary-cta" onClick={()=>setOpen(false)}>Gotowe — wracam do gry</button></footer></dialog>;
}
