export type IssueEffects = { teamPlan?: string; pressures?: Record<string, number>; burnout?: number; teamMorale?: number; teamFatigue?: number; relation?: number; readiness?: number; reputation?: number; unavailable?: { min: number; max: number; rounds: number; reason: string } };
export type ResolvedIssueEffects = Omit<IssueEffects, "unavailable"> & { unavailable?: { count: number; rounds: number; reason: string } };
export type IssueChoice = { id: string; label: string; feedback: string; effects: IssueEffects };
export type CareerIssue = { id: string; templateId?:string; story?:{arcId:string;step:number;clubId:string}; category: string; title: string; body: string; choices: IssueChoice[]; resolved: boolean };
export const EVENT_POOL: Array<{ id: string; title: string; category: string; from: number; to: number; weight?: number; minRound?: number; maxRound?: number; results?: Array<"win" | "draw" | "loss">; choices: IssueChoice[] }>;
export function generateRoundIssues(input: { seed: number; round: number; tier: number; result: "win" | "draw" | "loss"; worldHumor: number; recentTitles?: string[]; recentCategories?: string[]; maxEvents?: number }): { seed: number; events: CareerIssue[] };
export function welcomeIssue(clubName: string, coachFirstName: string, expectation: string, environmentStatus: string, environmentWork: string): CareerIssue;
export function legacyIssue(item: Partial<CareerIssue> & { id: string; title: string; body: string; resolved: boolean }): CareerIssue;
export function previewIssueEffects(effects: IssueEffects): string[];
export function resolveIssueEffects(seed: number, effects: IssueEffects): { seed: number; effects: ResolvedIssueEffects };
export function describeResolvedEffects(effects: ResolvedIssueEffects): string[];
