// Forty-eight original, distinct problems. Rows describe actual choices, not cosmetic title variants.
const rows = [
['keys',7,10,'Logistyka','organizacja','Klucze pojechały z kierownikiem','Kierownik ma klucze do magazynu, ale jest poza miejscowością. Rozgrzewkę można zacząć, części sprzętu nie da się wyjąć.','Zaczynam od pracy bez sprzętu|Przestawiam kolejność treningu|Proszę działaczy o zapasowy komplet'],
['dog',7,10,'Boisko','organizacja','Najaktywniejszy uczestnik ma cztery łapy','Pies regularnie wpada na boisko podczas treningu. Właściciel uważa, że zwierzak po prostu lubi futbol.','Przerywam grę i spokojnie zabezpieczamy wejście|Przenoszę ćwiczenie na drugą część obiektu|Proszę kierownika o rozmowę z właścicielem'],
['tractor',7,10,'Infrastruktura','organizacja','Koszenie weszło w mikrocykl','Konserwator może skosić boisko tylko w czasie zaplanowanej sesji. Trawa jest wysoka, terminarz krótki.','Skracam zajęcia boiskowe|Zmieniam kolejność akcentów|Uzgadniam koszenie strefami'],
['wedding',7,10,'Dostępność','ludzie','Wesele w kalendarzu drużyny','Dwóch zawodników zgłosiło wcześniej rodzinne wesele. Kierownik dopiero teraz połączył datę z meczem.','Akceptuję ich nieobecność|Proszę ich o indywidualne ustalenie udziału|Przygotowuję rotację i rezygnuję z nacisku'],
['harvest',8,10,'Dostępność','ludzie','Sezon poza boiskiem','Część drużyny ma więcej pracy zawodowej w najbliższych dniach. Frekwencja na treningu będzie niższa.','Skracam jednostkę do najważniejszych zadań|Zostawiam pełną sesję dla obecnych|Daję prosty plan do samodzielnego wykonania'],
['bus-turn',6,10,'Transport','organizacja','Autokar przy złym stadionie','Przewoźnik pomylił obiekty o podobnych nazwach. Na kolejny wyjazd potrzebuje jasnej procedury potwierdzania trasy.','Sam sprawdzam szczegóły kolejnego wyjazdu|Powierzam kontrolę kierownikowi|Proszę kapitana o dodatkowe potwierdzenie'],
['laundry',7,10,'Sprzęt','organizacja','Koszulki jeszcze schodzą z suszarki','Stroje nie wyschły na czas. Klub ma zapasowy komplet, ale zawodnicy nie są przyzwyczajeni do jego rozmiarów.','Organizuję zapasowy komplet z wyprzedzeniem|Ograniczam odprawę, żeby zyskać czas|Deleguję sprawę i chronię przygotowanie'],
['cones',7,10,'Trening','taktyka','Pachołki w innej sekcji','Sprzęt pożyczyła inna grupa. Możesz zmienić ćwiczenie bez strat czasu albo zorganizować brakujące oznaczenia.','Upraszczam ćwiczenie do gry|Odtwarzam ustawienie innym sprzętem|Daję zespołowi krótkie zadanie i reorganizuję sesję'],
['grill',7,10,'Społeczność','media','Mecz z menu degustacyjnym','Klubowy piknik ma przyciągnąć rodziny. Organizator chce obecności całej drużyny tuż po treningu.','Ustalam krótki udział reprezentacji zespołu|Pozwalam zawodnikom wybrać udział|Proponuję udział w spokojniejszym terminie'],
['whatsapp',7,10,'Komunikacja','ludzie','Trzy grupy i cztery godziny zbiórki','Informacja o zbiórce krąży w kilku komunikatorach. Każda wersja ma pewne źródło i inną godzinę.','Wprowadzam jedno oficjalne ogłoszenie|Proszę kapitana o potwierdzenia|Osobiście kontaktuję się z grupą'],
['floodlight',5,10,'Zaplecze','organizacja','Jeden reflektor ma wolne','Część oświetlenia nie działa. Bezpieczna powierzchnia treningowa jest mniejsza niż zwykle.','Zmieniam zadanie na mniejszą przestrzeń|Skracam pracę boiskową|Dzielę zespół na krótsze bloki'],
['exam',5,10,'Młodzież','rozwoj','Egzamin ważniejszy od odprawy','Młodsi zawodnicy mają intensywny tydzień nauki. Chcą jasnych zasad łączenia szkoły z treningiem.','Ustalam krótsze obowiązki na ten tydzień|Proszę o indywidualne zgłoszenia|Chronię wspólny trening, ograniczam odprawy'],
['changing-room',5,10,'Zaplecze','ludzie','Nowi mają miejsce przy drzwiach','Szatnia ma swoją niepisaną hierarchię. Nowi zawodnicy czują, że ich miejsce mówi więcej niż odprawa.','Rozmawiam z liderami o włączeniu nowych|Mieszam grupy w zadaniach treningowych|Daję nowym własny głos na odprawie'],
['birthday',5,10,'Szatnia','ludzie','Urodziny po terminie','Drużyna chce zorganizować wspólne spotkanie. Proponowany termin wypada tuż przed ważniejszym mikrocyklem.','Szukam spokojniejszego terminu|Ustalam krótki wspólny udział|Zostawiam organizację kapitanowi'],
['weekend-shift',7,10,'Dostępność','ludzie','Nagłe zastępstwo w pracy','Zawodnik dostał nieplanowaną zmianę. Informuje o tym wcześnie, ale wypada z przygotowań do najbliższego meczu.','Akceptuję nieobecność i planuję zastępstwo|Zmieniam akcent treningu dla dostępnych|Rozmawiam o wcześniejszym zgłaszaniu ograniczeń'],
['touchline-parent',5,10,'Otoczenie','media','Rodzina komentuje z trybuny','Bliska osoba jednego z piłkarzy głośno ocenia jego rolę. Zawodnik jest skrępowany, reszta słyszy komentarze.','Rozmawiam dyskretnie z zawodnikiem|Proszę klub o zasady przy treningu|Zostawiam rozmowę kapitanowi'],
['local-derby-map',5,10,'Rywal','taktyka','Znajomy zna znajomego rywala','Działacz przyniósł wiadomości o przeciwniku. Część jest użyteczna, część pochodzi z rozmowy sprzed kilku sezonów.','Sprawdzam tylko aktualne wskazówki|Przygotowuję prosty własny plan|Porównuję informacje z dostępnym nagraniem'],
['borrowed-goals',7,10,'Organizacja','organizacja','Bramki są, kółek nie ma','Pomocnicze bramki trzeba przestawić bez uszkadzania murawy. Ustawienie sesji potrwa dłużej niż planowano.','Zmniejszam liczbę zmian organizacyjnych|Używam obecnego ustawienia boiska|Deleguję przygotowanie z wyprzedzeniem'],
['hydration',1,10,'Gotowość','zdrowie','Upał zmienia rachunek pracy','Sztab zgłasza wysoką temperaturę. Zwykłe obciążenie może kosztować więcej niż w poprzednim tygodniu.','Skracam najcięższy akcent|Utrzymuję cel, dodaję przerwy|Przesuwam część pracy na odprawę'],
['cold',5,10,'Gotowość','zdrowie','Zimny wieczór i długi bezruch','Zawodnicy stygną podczas zbyt długiego tłumaczenia ćwiczenia. Trzeba inaczej poprowadzić sesję.','Skracam instrukcje i zwiększam płynność|Upraszczam zadanie na dziś|Przenoszę omówienie poza boisko'],
['heavy-legs-new',1,10,'Obciążenia','zdrowie','Plan dobry, nogi nie nadążają','Obciążenie ostatnich dni jest widoczne. Najbliższy mikrocykl powinien uwzględnić stan grupy.','Wybieram regenerację|Zmniejszam objętość, zostawiam intensywność|Rozdzielam zadania według gotowości'],
['too-easy',1,10,'Trening','taktyka','Zespół wykonuje zadanie bez oporu','Ćwiczenie stało się przewidywalne. Wykonanie wygląda dobrze, ale nie zmusza do nowych decyzji.','Dodaję jeden warunek sytuacyjny|Przechodzę do swobodniejszej gry|Zostawiam powtórkę na utrwalenie'],
['silent-team',1,10,'Komunikacja','ludzie','Na boisku za cicho','Zespół wykonuje zadania, ale mało się komunikuje. Trener nie powinien być jedynym nadajnikiem na obiekcie.','Daję liderom prostą rolę komunikacyjną|Zmieniam pary i odpowiedzialności|Upraszczam wspólne sygnały'],
['video-short',1,10,'Analiza','taktyka','Nagranie kończy się przy najważniejszej akcji','Materiał z meczu ma lukę. Możesz oprzeć analizę na pozostałych fragmentach lub poszukać dodatkowych relacji.','Wyciągam tylko potwierdzone wnioski|Uzupełniam materiał rozmową ze sztabem|Przenoszę akcent na obserwację treningu'],
['young-confidence',1,10,'Młodzież','rozwoj','Talent zbyt mocno przeżywa ocenę','Młody zawodnik traktuje każdą uwagę jak ostateczny wyrok. Potrzebuje ram, nie ciągłego zapewniania o wielkiej przyszłości.','Daję jeden konkretny cel na tydzień|Proszę mentora o wsparcie|Omawiam z nim sposób udzielania uwag'],
['veteran-learning',1,10,'Szatnia','ludzie','Doświadczenie też potrzebuje aktualizacji','Starszy zawodnik pyta, po co zmieniać rozwiązanie, które kiedyś działało. Grupa czeka na Twoją reakcję.','Pokazuję różnicę na przykładzie|Zapraszam go do testu na treningu|Jasno wyznaczam wspólne wymaganie'],
['warmup-music',1,10,'Rytuały','ludzie','Playlista przejęła odprawę','Spór o muzykę stał się sporem o wpływ. Głośnik ma małą moc, ale duży udział w życiu szatni.','Ustalam prosty podział odpowiedzialności|Oddaję sprawę radzie drużyny|Chronię ciszę tylko w czasie odprawy'],
['meal-routine',1,6,'Regeneracja','zdrowie','Posiłek w niewygodnej godzinie','Plan wyjazdu utrudnia spokojny posiłek. Trzeba dopasować organizację do przygotowania, nie odwrotnie.','Koryguję harmonogram odprawy|Proszę logistykę o zmianę planu|Upraszczam przedmeczowe obowiązki'],
['data-gps',1,4,'Sztab','taktyka','Raport pełen czerwonych pól','Dane treningowe wyglądają alarmująco, ale sztab podejrzewa błąd pomiaru. Piłkarze już komentują wykres.','Sprawdzam dane przed zmianą obciążeń|Tymczasowo zmniejszam najcięższy akcent|Łączę obserwację i rozmowę z grupą'],
['press-title',1,4,'Media','media','Tytuł ostrzejszy od wypowiedzi','Nagłówek sugeruje konflikt. Pełna rozmowa była spokojniejsza. Zespół pyta, czy powinien reagować.','Wyjaśniam kontekst wewnętrznie|Proszę o rzeczowe sprostowanie|Nie dokładam publicznych komentarzy'],
['open-training',1,5,'Kibice','media','Otwarty trening czy zamknięty plan','Klub chce udostępnić zajęcia kibicom. Sztab planował wtedy pracę nad szczegółami meczu.','Otwieram fragment bez szczegółów planu|Chronię całą sesję|Proponuję inny termin spotkania'],
['board-chart',1,5,'Zarząd','zarzad','Prezentacja dłuższa od treningu','Zarząd oczekuje obszernego raportu sportowego. Trzeba wybrać poziom szczegółowości bez zaniedbania pracy z drużyną.','Pokazuję trzy najważniejsze wnioski|Przygotowuję pełne omówienie|Deleguję część analizy sztabowi'],
['recruit-fit',1,6,'Rekrutacja','zarzad','Dobre liczby, inne zadania','Dyrektor pyta o profil potencjalnego wzmocnienia. Parametry wyglądają dobrze, ale rola w poprzednim klubie była inna.','Wskazuję warunki dopasowania|Podkreślam potrzebę obecnej roli|Proszę o dodatkową obserwację'],
['press-slot',1,3,'Media','media','Telewizja zmienia godzinę rozmowy','Rozmowa medialna koliduje z przygotowaniem zespołu. Klub chce współpracować z nadawcą i chronić rytm pracy.','Ustalam krótszą rozmowę|Przenoszę odprawę sztabu|Proszę o zastępstwo rzecznika'],
['staff-credit',1,5,'Sztab','ludzie','Sukces ma wielu autorów','Asystent uważa, że jego wkład zniknął w publicznej ocenie pracy. Nie chodzi o medale, lecz o poczucie wpływu.','Doceniam konkretną pracę przy sztabie|Oddaję mu fragment publicznego omówienia|Ustalam lepszy podział odpowiedzialności'],
['bench-temperature',1,10,'Szatnia','ludzie','Rezerwowi mają własną odprawę','Gracze rzadziej wykorzystywani zaczynają trzymać się osobno. Potrzebują uczciwego planu, nie kolejnego hasła o szerokiej kadrze.','Wybieram rotację na najbliższy mecz|Wyjaśniam mierzalne kryteria wyboru|Poświęcam im osobny fragment treningu'],
['rival-feint',1,10,'Rywal','taktyka','Przeciwnik zmienił zwyczaj','Ostatni mecz rywala różni się od poprzednich nagrań. Nie wiadomo, czy to trwała zmiana, czy rozwiązanie pod konkretnego przeciwnika.','Przygotowuję prosty wariant awaryjny|Zostaję przy głównym planie|Sprawdzam najnowsze fragmenty ze sztabem'],
['rookie-coach',5,10,'Rozwój sztabu','rozwoj','Młody trener prosi o praktykę','Kandydat chce obserwować zajęcia. Może pomóc, ale wymaga opieki i jasnych granic dostępu do drużyny.','Daję mu konkretne zadanie obserwacyjne|Zapraszam na wybrane zajęcia|Najpierw omawiam zasady ze sztabem'],
['sponsor-post',3,10,'Sponsor','media','Partner opublikował własną zapowiedź','Sponsor zapowiedział pewne zwycięstwo. Drużyna nie uczestniczyła w układaniu tego planu marketingowego.','Oddzielam przekaz sportowy od reklamy|Spokojnie koryguję oczekiwania|Proszę zarząd o wspólne zasady komunikacji'],
['club-photo',1,10,'Promocja','organizacja','Zdjęcie drużyny bez wspólnego terminu','Klub potrzebuje aktualnej fotografii. Sesja ma potrwać chwilę, ale każdy rozumie chwilę inaczej.','Wyznaczam krótki termin przed lekką sesją|Proszę klub o osobną organizację|Włączam zdjęcie w dzień otwarty'],
['family-week',1,10,'Życie trenera','zdrowie','Dom też ma terminarz','Bliscy zwracają uwagę, że klub zajmuje wszystkie wolne wieczory. Trzeba ochronić część czasu bez porzucania obowiązków.','Rezerwuję jeden wieczór bez klubu|Deleguję część przygotowań|Kończę pilne sprawy i skracam resztę planu'],
['motivation-copy',1,10,'Motywacja','ludzie','Drużyna zna przemowę na pamięć','Zawodnicy kończą zdanie, zanim skończysz mówić. Przekaz wymaga konkretu, a nie większej głośności.','Oddaję głos kapitanowi|Zostawiam dwa zadania meczowe|Rozmawiam z mniejszymi grupami'],
['winning-routine',1,10,'Forma','taktyka','Dobry wynik usypia czujność','Po zwycięstwie trening jest mniej skupiony. Nie chcesz karać za radość, ale standard pracy musi zostać.','Pokazuję dwa elementy do poprawy|Wprowadzam krótką rywalizację|Zostawiam lekki dzień i jasny plan jutra'],
['loss-silence',1,10,'Kryzys','ludzie','Po porażce każdy idzie w swoją stronę','Drużyna unika wspólnej oceny. Trzeba wrócić do rozmowy bez publicznego szukania winnych.','Rozmawiam najpierw z liderami|Robię krótkie wspólne omówienie|Przenoszę wnioski w zadania treningowe'],
['kit-colours',5,10,'Sprzęt','organizacja','Znaczniki w kolorze rywala','Drużyna żartuje z nowych znaczników. Problemem jest jednak słaby kontrast podczas wieczornych zajęć.','Upraszczam podział i zadania|Szukam czytelniejszego kompletu|Zmieniam organizację małej gry'],
['train-late',5,10,'Dostępność','ludzie','Pociąg nie prowadzi pressingu','Dojazd części kadry stał się mniej przewidywalny. Wspólny początek sesji nie może opierać się na nadziei.','Układam początek niewymagający kompletu|Ustalam wcześniejsze potwierdzenia obecności|Przesuwam jeden kluczowy blok treningu'],
['press-legend',1,5,'Media','media','Ekspert pamięta inny futbol','Były zawodnik krytykuje Twój sposób gry. Jego opinia ma zasięg, ale odpowiadanie na każde zdanie zabierze tydzień.','Odpowiadam wyłącznie o własnej pracy|Zapraszam do rzeczowej rozmowy|Nie wchodzę w polemikę'],
['youth-seniors',1,10,'Rozwój','rozwoj','Dwa zespoły proszą o tych samych ludzi','Trener młodzieży i seniorów chcą tych samych zawodników na ważną sesję. Potrzebne jest ustalenie priorytetów.','Ustalam wspólny plan obciążeń|Chronię przygotowanie pierwszej drużyny|Szukam podziału zadań na tydzień']
];
const effects={organizacja:[{readiness:2,burnout:1},{burnout:-1,readiness:-1},{teamMorale:1,pressures:{personal:1}}],ludzie:[{relation:2,burnout:1},{readiness:1,teamMorale:-1},{teamMorale:1,readiness:-1}],taktyka:[{readiness:2,teamFatigue:1},{teamMorale:1,readiness:-1},{readiness:1,burnout:1}],zdrowie:[{teamFatigue:-3,readiness:-1},{readiness:1,teamFatigue:1},{teamFatigue:-1,burnout:1}],rozwoj:[{relation:2,burnout:1},{readiness:1,relation:-1},{teamMorale:1,readiness:-1}],media:[{pressures:{media:-2,personal:1}},{pressures:{fans:-2,media:2}},{pressures:{board:1,media:-1}}],zarzad:[{pressures:{dressing:-1,board:2}},{pressures:{board:-2,dressing:1}},{burnout:1,readiness:1}]};
const feedback={
 organizacja:['Przygotowanie odzyskało porządek. Koszt dodatkowej organizacji spadł na trenera.','Plan został odciążony. Zespół ma jednak mniej dopracowanych szczegółów.','Współpraca pomogła atmosferze. Trzeba jeszcze dopilnować ustaleń.'],
 ludzie:['Osobista rozmowa poprawiła relację, ale zajęła czas i energię.','Standard pracy jest wyraźniejszy. Nie wszyscy przyjęli go z zadowoleniem.','Grupa dostała więcej przestrzeni. Część przygotowania ustąpiła sprawom szatni.'],
 taktyka:['Zadanie stało się konkretniejsze, a praca dołożyła niewielkie obciążenie.','Swoboda pomogła atmosferze, lecz plan zawiera mniej szczegółów.','Dodatkowe sprawdzenie poprawiło przygotowanie kosztem czasu trenera.'],
 zdrowie:['Świeżość wzrosła. Mniejszy bodziec oznacza również mniej pracy nad planem.','Przygotowanie zyskało, ale grupa odczuwa dodatkowe obciążenie.','Zespół został częściowo odciążony. Organizacja wymagała Twojej uwagi.'],
 rozwoj:['Wsparcie zostało zauważone. Trener poświęcił na nie dodatkową energię.','Priorytet sportowy jest jasny. Zainteresowani liczyli na więcej wyrozumiałości.','Porozumienie poprawiło atmosferę i ograniczyło czas pracy nad detalami.'],
 media:['Przekaz stał się spokojniejszy. Odpowiedzialność za jego utrzymanie została przy Tobie.','Otoczenie dostało odpowiedź, a media kolejny punkt zaczepienia.','Klub musi przejąć część komunikacji. Zainteresowanie trenerem chwilowo osłabło.'],
 zarzad:['Zespół dostał wsparcie, ale zarząd oczekuje mocniejszego uzasadnienia.','Prezes przyjął rozwiązanie spokojniej. W szatni pozostały pytania.','Weryfikacja poprawiła przygotowanie decyzji i zajęła dodatkowy czas.']};
export const ENVIRONMENT_EVENTS=rows.map(([id,from,to,category,kind,title,body,labels])=>({id:`env-${id}`,from,to,category,title,body,choices:labels.split('|').map((label,i)=>({id:`option-${i}`,label,feedback:feedback[kind][i],effects:structuredClone(effects[kind][i])}))}));
for(const e of ENVIRONMENT_EVENTS){
 if(e.id==='env-winning-routine')e.results=['win'];
 if(e.id==='env-loss-silence')e.results=['loss'];
 if(e.id==='env-heavy-legs-new')e.condition='fatigue';
 if(e.id==='env-family-week')e.condition='burnout';
 if(e.id==='env-wedding'){e.choices[0].effects.unavailable={min:2,max:2,rounds:1,reason:'uroczystość rodzinna'};e.choices[2].effects.teamPlan='ROTATION';e.choices[2].effects.unavailable={min:2,max:2,rounds:1,reason:'uroczystość rodzinna'};}
 if(e.id==='env-weekend-shift')e.choices[0].effects.unavailable={min:1,max:1,rounds:1,reason:'zmiana w pracy'};
 if(e.id==='env-bench-temperature')e.choices[0].effects.teamPlan='ROTATION';
}
