export type RatingPlayer = { id: string; primary: string; secondary: string[]; baseOVR: number; form: number; morale: number; fatigue: number; relation: number; injuryWeeks?: number };
export type PolicyEffect = { label: string; short: string; matchStrength: number; fatigue: number; morale: number; burnout: number };
export const POLICY_EFFECTS: Record<string, PolicyEffect>;
export function clamp(value: number, min: number, max: number): number;
export function normalizeStartingLicense(value: unknown): "Grassroots C" | "UEFA B" | "UEFA A" | "UEFA PRO";
export function requiredLicenseForTier(tier: number): "Grassroots C" | "UEFA B" | "UEFA A" | "UEFA PRO";
export function requiredLicenseForCompetition(competition: string): "Grassroots C" | "UEFA B" | "UEFA A" | "UEFA PRO";
export function licenseCoversTier(license: unknown, tier: number): boolean;
export function licenseCoversCompetition(license: unknown, competition: string): boolean;
export function coachingExperienceEligibility(age: number, playingExperience: string, coachingExperience: string): { eligible: boolean; availableYears: number; reason: string };
export function highestEligibleCoachingExperience(age: number, playingExperience: string): string;
export function startingLicenseEligibility(license: string, playingExperience: string, coachingExperience: string, age?: number): { eligible: boolean; reason: string };
export function highestEligibleStartingLicense(playingExperience: string, coachingExperience: string, age?: number): "Grassroots C" | "UEFA B" | "UEFA A" | "UEFA PRO";
export function readinessStrengthImpact(readiness: number): number;
export function tacticalPlanImpact(tactic: Record<string, string>, averageCondition?: number, readiness?: number): number;
export function buildMatchStrength(input: { lineupOVR: number; readiness: number; coachTactics: number; averageCondition: number; tactic: Record<string, unknown>; policyStrength?: number; burnout?: number; incidentPenalty?: number }): { factors: Record<string, number>; total: number };
export function pressureDeltaForResult(result: "win" | "draw" | "loss", multiplier: number): number;
export function capReadiness(current: number, gain: number, cap: number): number;
export function environmentIncidentOccurs(roll: number, risk: number): boolean;
export function weeklyBurnoutDelta(input: { result: "win" | "draw" | "loss"; intensity: string; recovery: boolean; policyBurnout: number; pressure: number; profile: string }): number;
export function burnoutMatchPenalty(burnout: number): number;
export function conditionFromFatigue(fatigue: number): number;
export function injuryRiskFromFatigue(fatigue: number, intensity?: string): number;
export function goalSatisfied(goalId: string, context: { readiness: number; averageMorale: number; positiveDecision?: boolean; analysisAttempted?: boolean; analysisImproved?: boolean; preMatchPressure: number; result: "win" | "draw" | "loss"; newPointFormation?: boolean; newYouthStarter?: boolean }): boolean;
export function resolveProfileScores<T extends string>(profiles: readonly T[], questions: Array<{ id: string; choices: Array<{ scores: Partial<Record<T, number>> }> }>, answers: Record<string, number>): T;
export function rngNext(seed: number): { value: number; seed: number };
export function normalizeSlot(slot: string): string;
export function positionPenalty(player: Pick<RatingPlayer, "primary" | "secondary">, slot: string): number;
export function liveBreakdown(player: RatingPlayer): { form: number; morale: number; relation: number; fatigue: number; total: number };
export function liveOVR(player: RatingPlayer): number;
export function effectiveOVR(player: RatingPlayer, slot: string): number;
export function selectBestLineup(players: RatingPlayer[], slots: readonly string[]): Record<string, string>;
export type LeagueTeam = { id: string; name: string; ovr: number; played: number; won: number; drawn: number; lost: number; gf: number; ga: number; points: number; form?: number; morale?: number; fatigue?: number; lastFive?: string[] };
export function teamLiveStrength(team: LeagueTeam): number;
export type LeagueFixture = { round: number; date: string; home: string; away: string; played: boolean; homeGoals?: number; awayGoals?: number };
export function seasonRoundDates(roundCount: number, startYear?: number, tier?: number): string[];
export function buildSchedule(teamIds: string[], startYear?: number, tier?: number): LeagueFixture[];
export function winterBreakDays(fixtures: LeagueFixture[]): number;
export function offseasonBaseChange(player: { age: number; baseOVR: number; potential: number }, roll: number): number;
export function shouldRetirePlayer(age: number, roll: number): boolean;
export function offseasonBurnout(burnout: number): number;
export function dismissalProbability(input: { place: number; teamCount: number; boardPressure: number; patience: number; unpredictability: number }): number;
export function updateTeamResult(teams: LeagueTeam[], home: string, away: string, homeGoals: number, awayGoals: number): LeagueTeam[];
export function sortedTable(teams: LeagueTeam[]): LeagueTeam[];
export function simulateMatchPlan(seed: number, homeStrength: number, awayStrength: number, homeName?: string, awayName?: string): {
  seed: number; events: Array<{ minute: number; text: string; kind: "goal" | "card" | "chance" | "info"; side: "home" | "away" | "neutral" }>;
  homeGoals: number; awayGoals: number; shotsHome: number; shotsAway: number; possessionHome: number; homeXg: number; awayXg: number; expected: { home: number; draw: number; away: number };
};
export function expectedOutcomeProbabilities(homeXg: number, awayXg: number): { home: number; draw: number; away: number };
export function diagnoseMatchOutcome(input: { result: "win" | "draw" | "loss"; readiness: number; expectedWin: number; expectedLoss: number; userGoals: number; opponentGoals: number; userXg: number; opponentXg: number; userShots: number; opponentShots: number }): string;
