// Original football situations. Each arc has three authored episodes, not title permutations.
const arcs = [
['shifts',7,10,'Dostępność','ludzie',
 ['Grafik nie zna terminarza','Trzech zawodników pracuje w jednym zakładzie. Nowy grafik koliduje z treningiem. Kierownik drużyny przyniósł tabelę; po raz pierwszy trudniejszą od ligowej.','Przesuwam jedną sesję|Zostawiam termin i pracuję z obecnymi|Ustalam indywidualny plan dla zmianowych'],
 ['Dwie grupy, jedna drużyna','Grupa poranna i wieczorna inaczej rozumieją nowe ustawienie. Wspólna odprawa może połączyć pracę, ale zabierze wolny wieczór.','Prowadzę krótką wspólną odprawę|Upraszczam zadania na mecz|Liderzy przekazują ustalenia'],
 ['Stały termin czy stały spór','Klub chce zamknąć grafik na kolejne tygodnie. Wszyscy potrzebują przewidywalności, lecz jednego idealnego terminu nie ma.','Utrzymuję dwa warianty tygodnia|Ustalam jeden termin z wyprzedzeniem|Oddaję część planowania kapitanowi']],
['volunteers',7,10,'Wolontariusze','organizacja',
 ['Człowiek od wszystkiego','Kierownik pierze stroje, zamawia autokar i prowadzi protokół. Zapowiada, że w niedzielę chciałby również obejrzeć mecz.','Przejmuję odprawę organizacyjną|Dzielę zadania między drużynę|Proszę prezesa o dodatkową osobę'],
 ['Pomoc ma własne pomysły','Nowi pomocnicy chcą robić wszystko inaczej. Dotychczasowy kierownik czuje, że zabrano mu klub.','Ustalam z nim podział odpowiedzialności|Daję nowym pełną samodzielność|Na razie ograniczam zmiany'],
 ['Kto zamyka szatnię','Przed kolejnym wyjazdem trzeba wskazać stałego koordynatora. Sam entuzjazm nie prowadzi kalendarza.','Wybieram jednego koordynatora|Zostawiam dyżury rotacyjne|Biorę nadzór do końca rundy']],
['youth-path',1,10,'Młodzież','rozwoj',
 ['Młodzi pytają o drzwi','Grupa młodych trenuje dobrze, ale nie rozumie swojej drogi do składu. Piłki noszą już szybciej niż seniorzy zmieniają zdanie.','Zapowiadam mecz młodzieży|Podaję kryteria i termin oceny|Łączę młodych w pary z mentorami'],
 ['Pierwsza ocena młodych','Sztab sprawdził postępy. Odwaga rośnie szybciej niż powtarzalność, a starsi przypominają o wyniku.','Podtrzymuję plan z młodzieżą|Na ten tydzień wybieram rotację|Najpierw poprawiam współpracę z seniorami'],
 ['Rozwój potrzebuje ciągłości','Akademia oczekuje stałej ścieżki. Masz ustalić rolę młodzieży bez obiecywania każdemu kariery reprezentanta.','Utrwalam miejsce młodych w planie|Łączę szanse z oceną treningu|Pozostawiam elastyczny dobór na każdy mecz']],
['captain-voice',1,10,'Kapitan','ludzie',
 ['Dwa głosy w szatni','Kapitan popiera Twój plan publicznie, a na treningu sugeruje inny. Zawodnicy słyszą dwie odprawy w cenie jednej.','Rozmawiam z nim bez świadków|Wyjaśniam zasady przy drużynie|Proszę go o konkretną kontrpropozycję'],
 ['Lider chce odpowiedzialności','Kapitan wraca z uwagami zespołu. Część jest trafna, część chroni wygodę starszych graczy.','Wdrażam jedną sprawdzalną zmianę|Bronię planu i tłumaczę powody|Oddaję liderom fragment odprawy'],
 ['Opaska i granice','Drużyna pyta, gdzie kończy się głos kapitana, a zaczyna decyzja trenera. Potrzebuje jasnego ustalenia.','Ustalam stały rytm konsultacji|Decyzję sportową zostawiam sobie|Daję radzie drużyny większą rolę']],
['bonus-talk',3,7,'Premie','zarzad',
 ['Premia w trzech wersjach','Zespół i prezes pamiętają inne ustalenia dotyczące premii. W klubie są trzy wersje rozmowy i żadnej notatki.','Proszę o wspólne spisanie ustaleń|Bronię oczekiwań szatni|Najpierw sprawdzam stanowisko prezesa'],
 ['Pieniądze wracają na odprawę','Rozmowa o premii odciąga uwagę od rywala. Trener nie ustala przelewów, ale odpowiada za skupienie drużyny.','Oddzielam rozmowę finansową od odprawy|Daję zespołowi przestrzeń na pytania|Proszę prezesa o osobiste wyjaśnienie'],
 ['Jasność przed następną rundą','Klub chce uniknąć powtórki. Potrzebna jest zasada komunikacji, nie kolejna obietnica bez pokrycia.','Pilnuję wspólnego komunikatu|Zostawiam negocjacje przedstawicielom zespołu|Kończę własny udział w rozmowach']],
['shared-pitch',5,10,'Boisko','organizacja',
 ['Trawa dla wszystkich','Pierwszy zespół, juniorzy i gminna impreza mają rezerwację na tę samą godzinę. Murawa jako jedyna nie potwierdziła obecności.','Przenoszę część pracy poza boisko|Negocjuję podział stref|Domagam się pierwszeństwa seniorów'],
 ['Linie po weekendzie','Po intensywnym użyciu boiska najgorszy jest środek. Trzeba zdecydować, ile jakości treningu poświęcić dla ochrony nawierzchni.','Pracujemy krócej w bocznych strefach|Zmieniam akcent na odprawę|Utrzymuję sesję z mniejszą intensywnością'],
 ['Kalendarz murawy','Administrator prosi o wspólny plan korzystania z obiektu. Możesz zyskać stabilność kosztem elastyczności.','Ustalam stałe dni z grupami młodzieży|Zostawiam sobie zmienne okna|Oddaję ustalenia kierownikowi']],
['recovery-room',5,10,'Zaplecze','organizacja',
 ['Ciepła woda, zimny temat','Po treningu zabrakło ciepłej wody. Zawodnicy znają to ćwiczenie, ale nie chcą kolejnego powtórzenia.','Przenoszę cięższy trening na inny obiekt|Żądam terminu naprawy|Skracam sesję i uprzedzam drużynę'],
 ['Naprawa potrwa dłużej','Klub podał późniejszy termin remontu. Trzeba ułożyć kolejny tydzień bez przerzucania całego problemu na piłkarzy.','Łączę lżejszą pracę z regeneracją|Wracam do zwykłego obciążenia|Sam organizuję rozwiązanie tymczasowe'],
 ['Standard na przyszłość','Prezes pyta, jakie minimum zaplecza jest niezbędne. Lista potrzeb może być długa, ale czas zarządu jest krótki.','Wskazuję trzy pilne potrzeby|Bronię pełnej listy zespołu|Ustalam etapowy plan poprawy']],
['physio-load',1,6,'Zdrowie','zdrowie',
 ['Sztab medyczny podnosi rękę','Specjalista od przygotowania zgłasza kumulację obciążeń. Asystent chciał dołożyć pressing. Obie prezentacje mają przekonujące strzałki.','Wybieram tydzień regeneracji|Zmniejszam tylko ostatnią sesję|Dzielę obciążenia według potrzeb'],
 ['Świeżość kontra automatyzmy','Lżejszy tydzień nie rozwiązuje wszystkich problemów. Trzeba wybrać, na czym skupić ograniczony czas pracy.','Utrwalam dwa podstawowe zachowania|Wracam do mocniejszej sesji|Daję więcej odpowiedzialności sztabowi'],
 ['Jedna ocena obciążenia','Sztab proponuje stały przegląd gotowości. To dodatkowe spotkanie, które może zapobiec chaotycznym decyzjom.','Wprowadzam krótki cotygodniowy przegląd|Reaguję tylko na ostrzeżenia|Przekazuję prowadzenie przeglądu asystentowi']],
['media-leak',1,5,'Media','media',
 ['Odprawa wyszła z szatni','Fragment wewnętrznej odprawy trafił do mediów. Brakuje kontekstu, za to jest bardzo dobry nagłówek.','Wyjaśniam sprawę najpierw drużynie|Publicznie przywracam kontekst|Nie podsycam tematu wypowiedzią'],
 ['Pytanie o zaufanie','Dziennikarze pytają o przeciek. Piłkarze chcą wiedzieć, czy odprawy zmienią się w dochodzenie.','Ustalam zasady poufności bez oskarżeń|Ograniczam dostęp do odpraw|Proszę liderów o wewnętrzną rozmowę'],
 ['Komunikacja po burzy','Klub potrzebuje jasnego sposobu kontaktu z mediami. Nie każda wypowiedź powinna być obroną poprzedniej.','Wprowadzam krótkie wspólne ustalenia|Zostawiam większą swobodę zawodnikom|Wypowiadam się głównie sam']],
['agent-role',1,4,'Agenci','zarzad',
 ['Telefon po treningu','Przedstawiciel zawodnika prosi o gwarancję roli. W rozmowie słowo gwarancja pada częściej niż nazwisko rywala.','Opisuję kryteria bez gwarancji|Zapraszam zawodnika do rozmowy|Odsyłam sprawę kontraktu do dyrektora'],
 ['Rozmowa ma świadków','Sprawa roli zawodnika dotarła do szatni. Inni pytają, czy również potrzebują pełnomocnika do ustalenia składu.','Wyjaśniam wspólne kryteria|Rozmawiam wyłącznie z zainteresowanym|Proszę dyrektora o zamknięcie tematu'],
 ['Sport i kontrakt','Przed kolejnymi rozmowami klub chce ustalić granice kompetencji. Trener ma doradzać, ale nie obiecywać za wszystkich.','Spisuję ocenę sportową|Wspólnie wyjaśniamy rolę zawodnikowi|Oddzielam się od negocjacji']],
['sponsor-camera',1,10,'Sponsor','media',
 ['Sponsor zamawia uśmiech','Partner klubu proponuje nagranie reklamy po treningu. Scenariusz ma pięć stron, czas regeneracji jedną rubrykę.','Ustalam krótki limit nagrania|Oddaję sponsorowi cały termin|Wybieram niewielką grupę reprezentantów'],
 ['Jeszcze jedno ujęcie','Sponsor chce dogrywki, a szatnia przypomina o ustalonym czasie. Musisz pogodzić relację z partnerem i własne słowo.','Bronię uzgodnionego limitu|Szukam innego terminu|Proszę kapitana o mediację'],
 ['Granice współpracy','Prezes chce stałych zasad udziału drużyny w promocji. Współpraca pomaga klubowi, lecz powinna dać się zaplanować.','Zapisuję chronione dni przed meczem|Zostawiam decyzje zarządowi|Proponuję rotację obowiązków']],
['assistant',1,6,'Sztab','ludzie',
 ['Asystent chce własnego głosu','Asystent dobrze prowadzi ćwiczenia, ale na odprawach czeka na Twoje przyzwolenie. Prosi o większą samodzielność.','Oddaję mu jeden obszar gry|Najpierw wspólnie oceniamy sesję|Zostawiam centralne decyzje u siebie'],
 ['Dwa pomysły na pressing','Asystent proponuje rozwiązanie inne od Twojego. Zespół potrzebuje jasnej decyzji, nie konkursu autorskich schematów.','Testuję pomysł w ograniczonym zakresie|Łączę wybrane elementy obu planów|Podtrzymuję dotychczasowy wariant'],
 ['Podział pracy sztabu','Czas ustalić stałe odpowiedzialności. Delegowanie zwalnia Twój czas, ale wymaga oddania części kontroli.','Daję asystentowi stały obszar|Rotujemy odpowiedzialność|Sam zatwierdzam wszystkie szczegóły']],
['professional-step',4,7,'Profesjonalizacja','organizacja',
 ['Klub chce być zawodowy','Zarząd oczekuje większej liczby zajęć. Część kadry nadal pracuje poza futbolem. Ambicja nie skraca doby.','Wprowadzam zmianę etapami|Bronię obecnego rytmu|Różnicuję obowiązki według dostępności'],
 ['Pierwsze koszty zmiany','Nowy model ujawnił różne możliwości zawodników. Jedni chcą więcej pracy, inni obawiają się utraty miejsca.','Ustalam minimalny wspólny standard|Otwieram skład dla szerszej rotacji|Skupiam się na najbardziej dostępnych'],
 ['Jaki klub budujemy','Zarząd oczekuje oceny przejścia. Trzeba nazwać granice bez udawania, że same wymagania stworzą infrastrukturę.','Proponuję etapowy plan sportowy|Wskazuję warunki niezbędne do wzrostu|Priorytetem zostawiam bieżący wynik']],
['derby-memory',1,10,'Kibice','media',
 ['Derby zaczęły się wcześniej','Lokalne dyskusje rozkręciły temat derbów. Kibice proszą o otwarty trening, a sztab chce spokoju.','Otwieram krótki fragment treningu|Chronię cały tydzień przygotowań|Organizuję spotkanie kapitana z kibicami'],
 ['Słowa żyją dłużej niż mecz','Twoje wypowiedzi wracają w rozmowach o rywalizacji. Trzeba wybrać ton, który nie zamieni każdego tygodnia w derby.','Wracam do konkretów sportowych|Podkreślam lokalną tożsamość|Ograniczam wypowiedzi do minimum'],
 ['Rywalizacja zostaje w mieście','Klub chce utrzymać relację z kibicami po gorącym okresie. Nie każdy problem rozwiąże kolejny apel o walkę.','Proponuję stały kontakt przedstawicieli|Pozostawiam kontakt rzecznikowi|Organizuję spotkanie po treningu']],
['coach-rest',1,10,'Życie trenera','zdrowie',
 ['Telefon nie zna wolnego','Przez kilka dni odpowiadasz na klubowe sprawy do późna. Rano odprawa ma być krótka, ale Twoja cierpliwość już taka jest.','Wyznaczam wieczór bez telefonu|Kończę najpilniejsze sprawy osobiście|Przekazuję część kontaktów sztabowi'],
 ['Odpoczynek potrzebuje granic','Klub przyzwyczaił się do Twojej stałej dostępności. Nowe granice wymagają uzgodnienia, nie samego wyciszenia telefonu.','Ustalam godziny pilnych kontaktów|Zostawiam bezpośredni numer liderom|Wracam do pełnej dostępności'],
 ['Rytm na dłuższą karierę','Wiesz już, które sprawy naprawdę wymagają Twojej reakcji. Trzeba zamienić tę wiedzę w codzienny zwyczaj.','Chronię stały blok odpoczynku|Deleguję raporty organizacyjne|Biorę większy nadzór na trudny okres']],
['club-legend',4,10,'Tradycja','ludzie',
 ['Legenda przy płocie','Były trener regularnie komentuje zajęcia. Ma zasługi i słuchaczy. Czasem również gwizdek.','Zapraszam go do spokojnej rozmowy|Wyznaczam granice przy treningu|Proszę go o pomoc w historii klubu'],
 ['Szacunek i wpływ','Starszy działacz wraca z własnymi uwagami o drużynie. Można skorzystać z doświadczenia bez oddawania prowadzenia zespołu.','Wybieram jedną trafną sugestię|Wyjaśniam różnicę ról|Rozmawiam wspólnie z prezesem'],
 ['Miejsce dla tradycji','Klub planuje spotkanie pokoleń. To szansa na więź z otoczeniem, ale także koszt czasu treningowego.','Włączam krótki udział drużyny|Deleguję kapitana i młodych|Chronię termin treningu']],
['club-stream',5,10,'Transmisja','media',
 ['Kamera za płotem','Wolontariusz chce transmitować mecze. Ma statyw, telefon i opinię o każdej zmianie. Klub pyta o zgodę na nagrania treningu.','Udostępniam tylko wybrany fragment|Ograniczam materiał do meczów|Ustalam zasady wspólnie z autorem'],
 ['Komentarz trafił do szatni','Fragment transmisji stał się tematem żartów. Jeden zawodnik odbiera go poważniej niż reszta.','Rozmawiam najpierw z zawodnikiem|Proszę o sprostowanie komentarza|Wyjaśniam temat całej grupie'],
 ['Obraz klubu w sieci','Transmisje mogą pomagać kibicom i analizie. Klub potrzebuje zasad, które nie zależą od aktualnego humoru komentatora.','Oddzielam analizę od promocji|Ustalam wspólny regulamin nagrań|Zostawiam promocję poza sztabem']],
['data-trust',1,5,'Analiza','taktyka',
 ['Dwie liczby, trzy interpretacje','Analityk i asystent inaczej odczytują ten sam mecz. Dane wskazują problem, ale nie wybierają rozwiązania.','Sprawdzam próbki nagrań z zespołem|Testuję małą korektę na treningu|Na razie ufam obserwacji boiskowej'],
 ['Raport kontra nawyk','Zawodnicy rozumieją wykresy, ale wracają do starych zachowań pod presją. Kolejna prezentacja może już nie pomóc.','Upraszczam zadania do dwóch sygnałów|Dokładam praktyczną powtórkę|Daję liderom wyjaśnić plan własnymi słowami'],
 ['Wiedza ma służyć grze','Sztab proponuje nowy standard raportu. Musisz wybrać, co rzeczywiście pomoże drużynie w tygodniu.','Ograniczam raport do trzech wniosków|Zostawiam pełną analizę dla sztabu|Włączam zespół w ocenę materiału']],
['return-group',1,10,'Powrót do rytmu','zdrowie',
 ['Różne tempo powrotu','Część kadry wraca po przerwach w treningu. Jedna wspólna sesja nie odpowiada wszystkim potrzebom.','Wybieram szerszą rotację|Upraszczam obciążenia całej grupy|Rozdzielam akcenty według gotowości'],
 ['Ambicja wyprzedza nogi','Zawodnicy chcą szybko odzyskać dawną rolę. Sztab przypomina, że gotowości nie da się zadeklarować na odprawie.','Bronię stopniowego powrotu|Sprawdzam ich w mocniejszej pracy|Daję lżejszy akcent i jasną ocenę'],
 ['Nowa hierarchia gotowości','Po kilku tygodniach trzeba ustalić uczciwe zasady wyboru. Dawna pozycja i obecna forma nie zawsze idą razem.','Wybieram aktualną gotowość|Chronię ciągłość zespołu|Rozszerzam rywalizację rotacją']],
['set-piece',1,10,'Stałe fragmenty','taktyka',
 ['Plan zapisany na serwetce','Asystent przynosi pomysł na stały fragment. W niższych ligach serwetka jest tablicą; wyżej tylko początkiem dłuższej prezentacji.','Daję pomysłowi jedną sesję|Najpierw upraszczam dotychczasowe warianty|Proszę liderów o ocenę wykonalności'],
 ['Rywale też oglądają','Powtarzany schemat staje się czytelny. Trzeba zmienić detal, niekoniecznie uczyć całej drużyny nowego alfabetu.','Dodaję jeden wariant wyjścia|Utrwalam podstawowe wykonanie|Zostawiam swobodę wykonawcom'],
 ['Ile schematów to za dużo','Zespół pyta, które rozwiązania są naprawdę obowiązujące. Notatnik rośnie szybciej niż czas na ćwiczenie.','Zostawiam dwa główne warianty|Utrzymuję szeroki zestaw|Oddaję wybór liderom formacji']],
['local-school',7,10,'Społeczność','rozwoj',
 ['Szkoła zaprasza drużynę','Lokalna szkoła prosi o wspólny trening. Termin wypada w napiętym tygodniu, ale dla klubu to ważna relacja.','Wysyłam kilku reprezentantów|Prowadzę krótkie spotkanie osobiście|Proponuję spokojniejszy termin'],
 ['Zainteresowanie po wizycie','Po spotkaniu młodzież pyta o klub, a działacze o regularną współpracę. Jednorazowa akcja zaczyna wymagać organizacji.','Łączę szkołę z trenerami młodzieży|Biorę koordynację na siebie|Ograniczam projekt do kilku spotkań'],
 ['Projekt potrzebuje opiekuna','Współpraca ma szansę przetrwać, jeśli nie będzie zależała wyłącznie od trenera seniorów.','Przekazuję projekt akademii|Zostaję opiekunem sportowym|Ustalam rotacyjny udział zespołu']],
['fan-expectation',1,6,'Oczekiwania','zarzad',
 ['Tabela przyspieszyła marzenia','Kibice dyskutują już o przyszłym sezonie. Zarząd chce, by trener podtrzymał entuzjazm, choć terminarz wciąż jest trudny.','Mówię o najbliższych zadaniach|Podkreślam ambicję zespołu|Łączę cel z warunkami rozwoju'],
 ['Cel wraca w każdym pytaniu','Dawna wypowiedź stała się punktem odniesienia. Nie chcesz odbierać wiary, ale musisz ochronić zespół przed deklaracjami.','Wyjaśniam zakres odpowiedzialności|Biorę presję publicznie na siebie|Proszę prezesa o wspólny przekaz'],
 ['Ocena bez zmieniania miarki','Przed kolejnym etapem sezonu trzeba ustalić, jak klub oceni pracę. Wynik jest ważny, lecz nie jedyny.','Ustalam mierzalne kryteria|Przyjmuję ocenę głównie przez wyniki|Pokazuję plan rozwoju zespołu']],
['language-room',1,5,'Komunikacja','ludzie',
 ['Odprawa w kilku językach','Nie wszyscy równie dobrze rozumieją szczegóły instrukcji. Potakiwanie działa międzynarodowo, asekuracja już nie zawsze.','Skracam komunikaty i pokazuję na boisku|Wyznaczam pomocników w parach|Przygotowuję prosty wspólny słownik'],
 ['Słowa trzeba sprawdzić w ruchu','Sztab widzi poprawę komunikacji, ale pod presją wracają nieporozumienia. Potrzebne jest utrwalenie prostych sygnałów.','Ćwiczymy kilka wspólnych komend|Pozwalam liderom prowadzić część sesji|Daję więcej czasu na odprawę'],
 ['Wspólny język drużyny','Grupa ma ustalić codzienny sposób porozumiewania. Nie chodzi o akcent, tylko o te same decyzje w tym samym momencie.','Utrwalam wspólne sygnały|Rotuję pary komunikacyjne|Oddaję nadzór kapitanowi']],
['travel-standard',1,5,'Podróże','organizacja',
 ['Plan wyjazdu na styk','Logistyka proponuje późniejszy wyjazd. Zespół zyska poranek w domu, ale straci margines na drogę i odpoczynek.','Bronię wcześniejszego wyjazdu|Akceptuję oszczędniejszy harmonogram|Proponuję krótszą odprawę przed podróżą'],
 ['Drużyna ocenia podróż','Po wyjeździe sztab i zawodnicy mają różne uwagi. Klub chce wiedzieć, co poprawić przed następną trasą.','Zbieram konkretną ocenę gotowości|Priorytetem zostawiam organizację klubu|Szukam kompromisu z kapitanem'],
 ['Stały standard wyjazdów','Można ustalić przewidywalne zasady. Koszt i regeneracja będą konkurować również po zakończeniu tej sprawy.','Ustalam minimalny czas odpoczynku|Różnicuję plan według długości trasy|Każdy wyjazd oceniam osobno']]
];
const effects = {
 ludzie:[{relation:2,teamMorale:1,burnout:1},{readiness:2,relation:-2,pressures:{dressing:1}},{burnout:-1,readiness:-1,pressures:{personal:1}}],
 organizacja:[{readiness:2,burnout:1},{burnout:-1,readiness:-1,pressures:{board:1}},{teamMorale:1,readiness:1,pressures:{personal:2}}],
 rozwoj:[{teamPlan:'YOUTH',teamMorale:1,readiness:-1},{readiness:1,relation:-1},{relation:2,burnout:1}],
 zarzad:[{pressures:{board:2,dressing:-2},burnout:1},{pressures:{board:-2,dressing:2},relation:-1},{pressures:{personal:2,board:-1},readiness:1}],
 media:[{pressures:{media:-2,personal:1},burnout:1},{pressures:{fans:-2,media:2},teamMorale:1},{pressures:{media:-1,fans:2},burnout:-1}],
 zdrowie:[{teamFatigue:-3,readiness:-1,burnout:-1},{readiness:2,teamFatigue:2,burnout:1},{teamFatigue:-1,teamMorale:1,burnout:1}],
 taktyka:[{readiness:2,burnout:1},{readiness:1,teamFatigue:2},{teamMorale:1,burnout:-1,readiness:-1}],
};
const followup = {
 ludzie:['Rozmowa dała ludziom poczucie udziału, ale teraz oczekują dalszej uwagi.','Jasne wymagania uporządkowały pracę. Zaufanie nadal wymaga rozmowy.','Podział odpowiedzialności odciążył trenera. Kontrola wspólnego kierunku pozostaje potrzebna.'],
 organizacja:['Lepsze przygotowanie kosztowało dodatkową pracę organizacyjną.','Ograniczenie wymagań oszczędziło czas, lecz pozostawiło część trudności.','Uzgodnienia pomogły drużynie, ale zwiększyły liczbę spraw do dopilnowania.'],
 rozwoj:['Większa rola młodzieży dała nadzieję i zmniejszyła margines doświadczenia.','Czytelne kryteria wspierają przygotowanie. Czekający na szansę nie są w pełni zadowoleni.','Wsparcie w relacjach pomogło grupie i zajęło czas trenera.'],
 zarzad:['Szatnia dostała wsparcie, lecz rozmowa z zarządem stała się trudniejsza.','Zarząd zyskał spokój, a część szatni oczekuje wyjaśnienia kosztu.','Kompromis poprawił organizację, ale wymagał Twojego osobistego zaangażowania.'],
 media:['Spokojniejszy przekaz kosztował czas i energię.','Otwartość pomogła relacji z kibicami, lecz powiększyła zainteresowanie mediów.','Mniejszy udział trenera ograniczył hałas medialny, pozostawiając pytania otoczenia.'],
 zdrowie:['Zmniejszenie obciążeń poprawiło świeżość kosztem części przygotowania.','Więcej pracy dało bodziec, ale dołożyło zmęczenia.','Indywidualne podejście odciążyło grupę i zwiększyło pracę organizacyjną.'],
 taktyka:['Dokładniejsza praca poprawiła gotowość, lecz zajęła Twój czas.','Powtarzanie pomogło przygotowaniu i dołożyło obciążenia.','Większa swoboda pomogła atmosferze, ale zostawiła mniej szczegółów w planie.'],
};
export const STORY_ARCS = arcs.map(([id,from,to,category,kind,...episodes])=>({id,from,to,category,kind,episodes:episodes.map(([title,body,labels],stage)=>({title,body,choices:labels.split('|').map((label,i)=>({id:['support','standards','delegate'][i],label,feedback:followup[kind][i],effects:structuredClone(effects[kind][i])}))}))}));
// Explicit sporting promises only when the selected answer actually promises a plan.
for(const arc of STORY_ARCS) for(const e of arc.episodes) for(const c of e.choices){
 if(arc.kind==='rozwoj' && !/mecz młodzieży|plan z młodzieżą|miejsce młodych/.test(c.label)) delete c.effects.teamPlan;
 if(/szerszą rotację|dla szerszej rotacji|wybieram rotację|rywalizację rotacją/.test(c.label)) c.effects.teamPlan='ROTATION';
}
export function storyCatalogStats(){return {arcs:STORY_ARCS.length,episodes:STORY_ARCS.reduce((n,a)=>n+a.episodes.length,0),choices:STORY_ARCS.reduce((n,a)=>n+a.episodes.reduce((s,e)=>s+e.choices.length,0),0)};}
